ALTER TABLE llx_societe ADD INDEX(client);
ALTER TABLE llx_societe ADD INDEX(fournisseur);
ALTER TABLE llx_societe ADD INDEX(parent);
ALTER TABLE llx_societe ADD INDEX(entity);
ALTER TABLE llx_societe ADD INDEX(fk_pays);
ALTER TABLE llx_societe ADD INDEX(fk_departement);
ALTER TABLE llx_contrat ADD INDEX(statut);
ALTER TABLE llx_contrat ADD INDEX(ref);
ALTER TABLE llx_contrat ADD INDEX(date_contrat);
ALTER TABLE llx_contrat ADD INDEX(entity);
ALTER TABLE llx_contratdet ADD INDEX(statut);
ALTER TABLE llx_contratdet ADD INDEX(statut, date_fin_validite);